
# Ingress configuration
ingress:
  host: longhorn.infra.qiu.family
  # configure cert-manager issuer
  certmanager:
    # tlsIssuer=letsecrypt to generate valid TLS certficiate using IONOS API
    # tlsIssuer=ca to generate a CA-signed certificate (not valid)
    tlsIssuer: letsencrypt
  # Enabling traefik basic authorization, reusing global middleware created for Traefik
  basicAuth:
    enable: true
    middlewareName: basic-auth
    middlewareNamespace: traefik

# Prometheus servicemonitor configuration
serviceMonitor:
  enable: true
  release: monitoring

#####################
# longhorn subchart
#####################

longhorn:
  defaultSettings:
    defaultDataPath: "/storage"
